/**
 * Generate the playground's `global.css` and `tailwind.config.js` from
 * `@hex-core/tokens`.
 *
 * This is the same pair `hex init --platform native` writes into a
 * consumer's app, produced by the same two functions — so the playground is
 * a dogfood of the CLI's native template rather than a hand-tuned copy of it.
 *
 *   pnpm --filter native-playground build:theme
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { defaultTheme, generateGlobalsCssNative, themeToTailwindConfig } from "@hex-core/tokens";

const HERE = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = join(HERE, "..");

const theme = themeToTailwindConfig(defaultTheme);

const tailwindConfig = `/** AUTO-GENERATED by scripts/build-theme.mts — do not edit. */
/** @type {import("tailwindcss").Config} */
module.exports = {
	darkMode: "class",
	content: [
		"./app/**/*.{ts,tsx}",
		"./src/**/*.{ts,tsx}",
		"../../packages/native/src/**/*.{ts,tsx}",
	],
	presets: [require("nativewind/preset")],
	theme: {
		extend: ${JSON.stringify(theme, null, "\t").replace(/\n/g, "\n\t\t")},
	},
	plugins: [],
};
`;

writeFileSync(join(APP_ROOT, "global.css"), `${generateGlobalsCssNative(defaultTheme)}\n`);
writeFileSync(join(APP_ROOT, "tailwind.config.js"), tailwindConfig);

console.log("✓ Wrote global.css and tailwind.config.js from @hex-core/tokens");
