/** AUTO-GENERATED by scripts/build-theme.mts — do not edit. */
/** @type {import("tailwindcss").Config} */
module.exports = {
	darkMode: "class",
	content: [
		"./app/**/*.{ts,tsx}",
		"./src/**/*.{ts,tsx}",
		"../../packages/native/src/**/*.{ts,tsx}",
	],
	presets: [require("nativewind/preset")],
	theme: {
		extend: {
			"colors": {
				"background": "hsl(var(--background))",
				"foreground": "hsl(var(--foreground))",
				"card": "hsl(var(--card))",
				"card-foreground": "hsl(var(--card-foreground))",
				"popover": "hsl(var(--popover))",
				"popover-foreground": "hsl(var(--popover-foreground))",
				"primary": "hsl(var(--primary))",
				"primary-foreground": "hsl(var(--primary-foreground))",
				"secondary": "hsl(var(--secondary))",
				"secondary-foreground": "hsl(var(--secondary-foreground))",
				"muted": "hsl(var(--muted))",
				"muted-foreground": "hsl(var(--muted-foreground))",
				"accent": "hsl(var(--accent))",
				"accent-foreground": "hsl(var(--accent-foreground))",
				"destructive": "hsl(var(--destructive))",
				"destructive-foreground": "hsl(var(--destructive-foreground))",
				"border": "hsl(var(--border))",
				"input": "hsl(var(--input))",
				"ring": "hsl(var(--ring))",
				"chart-1": "hsl(var(--chart-1))",
				"chart-2": "hsl(var(--chart-2))",
				"chart-3": "hsl(var(--chart-3))",
				"chart-4": "hsl(var(--chart-4))",
				"chart-5": "hsl(var(--chart-5))",
				"chart-6": "hsl(var(--chart-6))"
			},
			"borderRadius": {
				"radius": "var(--radius)"
			},
			"spacing": {
				"1": "var(--space-1)",
				"2": "var(--space-2)",
				"3": "var(--space-3)",
				"4": "var(--space-4)",
				"6": "var(--space-6)",
				"8": "var(--space-8)",
				"12": "var(--space-12)",
				"16": "var(--space-16)",
				"xs": "var(--gap-xs)",
				"sm": "var(--gap-sm)",
				"md": "var(--gap-md)",
				"lg": "var(--gap-lg)",
				"xl": "var(--gap-xl)"
			},
			"fontSize": {
				"xs": "var(--text-xs)",
				"sm": "var(--text-sm)",
				"base": "var(--text-base)",
				"lg": "var(--text-lg)",
				"xl": "var(--text-xl)",
				"2xl": "var(--text-2xl)",
				"3xl": "var(--text-3xl)"
			},
			"transitionDuration": {
				"fast": "var(--duration-fast)",
				"normal": "var(--duration-normal)",
				"slow": "var(--duration-slow)"
			},
			"height": {
				"container-sm": "var(--container-sm)",
				"container-md": "var(--container-md)",
				"container-lg": "var(--container-lg)",
				"container-xl": "var(--container-xl)",
				"height-sm": "var(--control-height-sm)",
				"height-md": "var(--control-height-md)",
				"height-lg": "var(--control-height-lg)"
			}
		},
	},
	plugins: [],
};
