/**
 * Snapshot test for `buildAppContext`. Runs as a standalone node script via
 * `pnpm -F \`@hex-core/payload\` test:app-context`. No test runner — the function
 * is pure and a format change should fail loudly here so it can be reviewed
 * deliberately.
 *
 * To update the snapshot: run the test, copy the actual output from stderr,
 * and replace EXPECTED below. Treat each update as a public-API change to
 * the LLM payload format and bump the changeset accordingly.
 *
 * All output (success AND failure) writes to stderr; stdout stays empty so
 * piping this into another command stays clean. CI consumers should capture
 * stderr to see the pass/fail summary.
 */

import type { Recipe } from "../loaders/recipe-loader.js";
import type { RegistryItem } from "../loaders/registry-loader.js";
import { buildAppContext } from "./app-context.js";

const fakeButton: RegistryItem = {
	name: "button",
	displayName: "Button",
	description: "Refined button with subtle shadow and micro-interactions.",
	category: "component",
	version: "1.0.0",
	framework: "react",
	props: [],
	variants: [],
	slots: [],
	files: [],
	// Two deps: one resolves to a slug ("popover"), one is filtered out as
	// non-component ("lib/utils"). Locks both internalDepToSlug behaviors.
	dependencies: { internal: ["components/popover/popover", "lib/utils"], npm: [] },
	tokensUsed: [],
	examples: [],
	ai: {},
	tags: ["form", "interaction"],
};

const fakeCard: RegistryItem = {
	name: "card",
	displayName: "Card",
	description: "Surface with header, body, and footer slots.",
	category: "component",
	version: "1.0.0",
	framework: "react",
	props: [],
	variants: [],
	slots: [],
	files: [],
	dependencies: { internal: [], npm: [] },
	tokensUsed: [],
	examples: [],
	ai: {},
	tags: ["layout"],
};

/**
 * A native item whose internal dep names the same source path a web item
 * would (`primitives/text/text`). Resolving that path without the owner's
 * platform sends a reader to the React DOM `text`, which is the bug this
 * fixture locks.
 */
const fakeNativeCard: RegistryItem = {
	name: "native-card",
	displayName: "Card",
	description: "Surface with header, body, and footer slots.",
	category: "component",
	version: "1.0.0",
	framework: "react",
	platform: "native",
	props: [],
	variants: [],
	slots: [],
	files: [],
	dependencies: { internal: ["primitives/text/text", "lib/utils"], npm: [] },
	tokensUsed: [],
	examples: [],
	ai: {},
	tags: ["layout", "native"],
};

const fakeRecipe: Recipe = {
	slug: "settings-page",
	title: "Settings page",
	summary: "Tabbed settings with section headers and a save button.",
	tags: ["form"],
	brief: "settings",
	steps: [
		{ component: "card", reason: "section container", role: "primary" },
		{ component: "button", reason: "save action", role: "supporting" },
	],
	checklist: [
		{
			id: "a11y-1",
			check: "Save button has descriptive label",
			severity: "blocker",
			source: "derived-a11y",
		},
	],
};

const fakeTheme = {
	name: "default",
	displayName: "Default",
	description: "A refined, neutral theme.",
	tokens: {
		// `space-4` and `control-height-md` deliberately overlap with DENSITY_VARS
		// keys so density-fold tests can assert that density wins on conflict
		// (would-be silent regression if `renderRule` printed both declarations
		// in the same `:root` rule and theme cascaded over density).
		light: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "240 10% 3.9%", type: "color" },
			primary: { value: "240 5.9% 10%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			destructive: { value: "0 84% 60%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			"duration-normal": { value: "200ms", type: "duration" },
			"space-4": { value: "1rem", type: "spacing" },
			"control-height-md": { value: "2.5rem", type: "dimension" },
		},
		dark: {
			background: { value: "240 10% 3.9%", type: "color" },
			foreground: { value: "0 0% 98%", type: "color" },
			primary: { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 5.9% 10%", type: "color" },
			destructive: { value: "0 62% 30%", type: "color" },
			radius: { value: "0.5rem", type: "radius" },
			"duration-normal": { value: "200ms", type: "duration" },
			"space-4": { value: "1rem", type: "spacing" },
			"control-height-md": { value: "2.5rem", type: "dimension" },
		},
	},
};

const EXPECTED_HAPPY = `# App context — Hex Core

Generated by \`emit_app_context\`. Paste this into your LLM chat as project context.

## Theme

**Default** (\`default\`) — A refined, neutral theme.

| Token | Value |
|---|---|
| \`--background\` | \`0 0% 100%\` |
| \`--foreground\` | \`240 10% 3.9%\` |
| \`--primary\` | \`240 5.9% 10%\` |
| \`--primary-foreground\` | \`0 0% 98%\` |
| \`--destructive\` | \`0 84% 60%\` |
| \`--radius\` | \`0.5rem\` |

_Values are raw — wrap in \`hsl(...)\` when consuming via Tailwind v4 \`@theme\`._

## globals.css

Replace your \`app/globals.css\` (or paste this into it) so every component reads the tokens above.

\`\`\`css
@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 240 10% 3.9%;
    --primary: 240 5.9% 10%;
    --primary-foreground: 0 0% 98%;
    --destructive: 0 84% 60%;
    --radius: 0.5rem;
    --duration-normal: 200ms;
    --space-4: 1rem;
    --control-height-md: 2.5rem;
  }

  .dark {
    --background: 240 10% 3.9%;
    --foreground: 0 0% 98%;
    --primary: 0 0% 98%;
    --primary-foreground: 240 5.9% 10%;
    --destructive: 0 62% 30%;
    --radius: 0.5rem;
    --duration-normal: 200ms;
    --space-4: 1rem;
    --control-height-md: 2.5rem;
  }
}
\`\`\`

## tailwind.config.ts

Add to your \`theme.extend\` so utility classes like \`p-4\` resolve to your tokens:

\`\`\`ts
export default {
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        destructive: "hsl(var(--destructive))",
      },
      borderRadius: {
        radius: "var(--radius)",
      },
      spacing: {
        "4": "var(--space-4)",
      },
      transitionDuration: {
        normal: "var(--duration-normal)",
      },
      height: {
        "height-md": "var(--control-height-md)",
      },
    },
  },
};
\`\`\`

## Components (2)

### Button \`button\`

Refined button with subtle shadow and micro-interactions.

Depends on: \`popover\`.

### Card \`card\`

Surface with header, body, and footer slots.

## Recipes (1)

### Settings page \`settings-page\`

Tabbed settings with section headers and a save button.

**Steps:**
1. \`card\` — section container _(primary)_
2. \`button\` — save action _(supporting)_

**Checklist:**
- [ ] Save button has descriptive label _(blocker)_

## Install

\`\`\`bash
npx @hex-core/cli@latest init
npx @hex-core/cli@latest add button card
\`\`\`

## Context prompt

You are building a Next.js 16 (App Router, Turbopack) app using @hex-core components.

Rules you must follow:

1. Use the exact tokens defined in \`globals.css\` above. Do not introduce new colors or spacing values that aren't in the token set.
2. Use \`@hex-core/components\` imports for all UI primitives — never re-implement Button / Card / Dialog / etc. in plain HTML.
3. For layout, prefer the layout primitives (\`Stack\`, \`Cluster\`, \`Container\`, \`Grid\`); fall back to Tailwind utilities mapped to spacing tokens (\`p-4\`, \`gap-2\`, etc.) when a primitive isn't a fit.
4. Honor the AI guidance in each component's \`.schema.ts\` — \`whenToUse\`, \`whenNotToUse\`, \`commonMistakes\`, \`accessibilityNotes\`.
5. Default to React Server Components; only add \`"use client"\` when needed (event handlers, hooks, browser APIs).
6. All interactive elements get \`transition-all duration-normal ease-out\` and \`focus-visible:ring-2\`.

Components in scope for this app: button, card.

Now: <your ask here, e.g. "build me a pricing page with three tiers">.`;

const EXPECTED_MISSING_SLUGS = `# App context — Hex Core

Generated by \`emit_app_context\`. Paste this into your LLM chat as project context.

## Theme

**Unknown theme** \`vaporwave\` — fall back to \`default\` and notify the user.

## Components (1)

> Missing: \`zoltan\`.

### Card \`card\`

Surface with header, body, and footer slots.

## Install

\`\`\`bash
npx @hex-core/cli@latest init
npx @hex-core/cli@latest add card
\`\`\`

## Context prompt

You are building a Next.js 16 (App Router, Turbopack) app using @hex-core components.

Rules you must follow:

1. Use the exact tokens defined in \`globals.css\` above. Do not introduce new colors or spacing values that aren't in the token set.
2. Use \`@hex-core/components\` imports for all UI primitives — never re-implement Button / Card / Dialog / etc. in plain HTML.
3. For layout, prefer the layout primitives (\`Stack\`, \`Cluster\`, \`Container\`, \`Grid\`); fall back to Tailwind utilities mapped to spacing tokens (\`p-4\`, \`gap-2\`, etc.) when a primitive isn't a fit.
4. Honor the AI guidance in each component's \`.schema.ts\` — \`whenToUse\`, \`whenNotToUse\`, \`commonMistakes\`, \`accessibilityNotes\`.
5. Default to React Server Components; only add \`"use client"\` when needed (event handlers, hooks, browser APIs).
6. All interactive elements get \`transition-all duration-normal ease-out\` and \`focus-visible:ring-2\`.

Components in scope for this app: card.

Now: <your ask here, e.g. "build me a pricing page with three tiers">.`;

const EXPECTED_RECIPES_ALL_MISSING = `# App context — Hex Core

Generated by \`emit_app_context\`. Paste this into your LLM chat as project context.

## Theme

**Default** (\`default\`) — A refined, neutral theme.

| Token | Value |
|---|---|
| \`--background\` | \`0 0% 100%\` |
| \`--foreground\` | \`240 10% 3.9%\` |
| \`--primary\` | \`240 5.9% 10%\` |
| \`--primary-foreground\` | \`0 0% 98%\` |
| \`--destructive\` | \`0 84% 60%\` |
| \`--radius\` | \`0.5rem\` |

_Values are raw — wrap in \`hsl(...)\` when consuming via Tailwind v4 \`@theme\`._

## globals.css

Replace your \`app/globals.css\` (or paste this into it) so every component reads the tokens above.

\`\`\`css
@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 240 10% 3.9%;
    --primary: 240 5.9% 10%;
    --primary-foreground: 0 0% 98%;
    --destructive: 0 84% 60%;
    --radius: 0.5rem;
    --duration-normal: 200ms;
    --space-4: 1rem;
    --control-height-md: 2.5rem;
  }

  .dark {
    --background: 240 10% 3.9%;
    --foreground: 0 0% 98%;
    --primary: 0 0% 98%;
    --primary-foreground: 240 5.9% 10%;
    --destructive: 0 62% 30%;
    --radius: 0.5rem;
    --duration-normal: 200ms;
    --space-4: 1rem;
    --control-height-md: 2.5rem;
  }
}
\`\`\`

## tailwind.config.ts

Add to your \`theme.extend\` so utility classes like \`p-4\` resolve to your tokens:

\`\`\`ts
export default {
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        destructive: "hsl(var(--destructive))",
      },
      borderRadius: {
        radius: "var(--radius)",
      },
      spacing: {
        "4": "var(--space-4)",
      },
      transitionDuration: {
        normal: "var(--duration-normal)",
      },
      height: {
        "height-md": "var(--control-height-md)",
      },
    },
  },
};
\`\`\`

## Components (1)

### Card \`card\`

Surface with header, body, and footer slots.

## Recipes (0)

> Missing: \`ghost-recipe\`.

## Install

\`\`\`bash
npx @hex-core/cli@latest init
npx @hex-core/cli@latest add card
\`\`\`

## Context prompt

You are building a Next.js 16 (App Router, Turbopack) app using @hex-core components.

Rules you must follow:

1. Use the exact tokens defined in \`globals.css\` above. Do not introduce new colors or spacing values that aren't in the token set.
2. Use \`@hex-core/components\` imports for all UI primitives — never re-implement Button / Card / Dialog / etc. in plain HTML.
3. For layout, prefer the layout primitives (\`Stack\`, \`Cluster\`, \`Container\`, \`Grid\`); fall back to Tailwind utilities mapped to spacing tokens (\`p-4\`, \`gap-2\`, etc.) when a primitive isn't a fit.
4. Honor the AI guidance in each component's \`.schema.ts\` — \`whenToUse\`, \`whenNotToUse\`, \`commonMistakes\`, \`accessibilityNotes\`.
5. Default to React Server Components; only add \`"use client"\` when needed (event handlers, hooks, browser APIs).
6. All interactive elements get \`transition-all duration-normal ease-out\` and \`focus-visible:ring-2\`.

Components in scope for this app: card.

Now: <your ask here, e.g. "build me a pricing page with three tiers">.`;

interface Case {
	name: string;
	build: () => string;
	expected?: string;
	contains?: string[];
	excludes?: string[];
}

/**
 * Extract the contents of the `:root { ... }` block from an `emit_app_context`
 * output so density-cascade assertions don't leak into the `.dark` block (which
 * intentionally inherits theme defaults regardless of `density`).
 * @param markdown - Full `buildAppContext` output
 * @returns The raw `:root { ... }` body, or empty string if no `:root` rule found
 */
function extractRootBlock(markdown: string): string {
	const start = markdown.indexOf("  :root {");
	if (start === -1) return "";
	const end = markdown.indexOf("  }", start);
	return end === -1 ? markdown.slice(start) : markdown.slice(start, end);
}

const CASES: Case[] = [
	{
		name: "happy path: theme + 2 components + 1 recipe",
		build: () =>
			buildAppContext({
				theme: { requested: "default", resolved: fakeTheme },
				components: [
					{ slug: "button", item: fakeButton },
					{ slug: "card", item: fakeCard },
				],
				recipes: [{ slug: "settings-page", recipe: fakeRecipe }],
			}),
		expected: EXPECTED_HAPPY,
	},
	{
		name: "missing theme + missing component slug",
		build: () =>
			buildAppContext({
				theme: { requested: "vaporwave", resolved: null },
				components: [
					{ slug: "card", item: fakeCard },
					{ slug: "zoltan", item: null },
				],
				recipes: [],
			}),
		expected: EXPECTED_MISSING_SLUGS,
	},
	{
		name: "recipes supplied but all unknown",
		build: () =>
			buildAppContext({
				theme: { requested: "default", resolved: fakeTheme },
				components: [{ slug: "card", item: fakeCard }],
				recipes: [{ slug: "ghost-recipe", recipe: null }],
			}),
		expected: EXPECTED_RECIPES_ALL_MISSING,
	},
	{
		name: "native item resolves its internal deps to the native catalog",
		build: () =>
			buildAppContext({
				theme: { requested: "default", resolved: fakeTheme },
				components: [{ slug: "native-card", item: fakeNativeCard }],
				recipes: [],
				itemExists: (name) => name === "native-text",
			}),
		contains: ["Depends on: `native-text`."],
		// The bare slug is what the platform-blind resolver used to emit, and
		// it points at the React DOM component of the same name.
		excludes: ["`text`.", "lib/utils"],
	},
	{
		name: "an all-native component set gets the React Native prompt, not the Next.js one",
		build: () =>
			buildAppContext({
				theme: { requested: "default", resolved: fakeTheme },
				components: [{ slug: "native-card", item: fakeNativeCard }],
				recipes: [],
				itemExists: (name) => name === "native-text",
			}),
		contains: [
			"React Native app (Expo)",
			"init --platform native",
			"<PortalHost />",
			"onPress`, not `onClick",
		],
		// The web rules describe a platform this app does not run on, and the
		// emitted globals.css would be a var() chain React Native cannot
		// resolve — worse than absent, because it silently yields no colour.
		excludes: [
			"Next.js 16 (App Router, Turbopack)",
			"React Server Components",
			"focus-visible:ring-2",
			"## tailwind.config.ts",
		],
	},
	{
		name: "a mixed-platform set is called out rather than rendered as one",
		build: () =>
			buildAppContext({
				theme: { requested: "default", resolved: fakeTheme },
				components: [
					{ slug: "card", item: fakeCard },
					{ slug: "native-card", item: fakeNativeCard },
				],
				recipes: [],
			}),
		contains: ["Mixed platforms", "Next.js 16 (App Router, Turbopack)"],
	},
	{
		name: "web item keeps bare slugs when no catalog predicate is supplied",
		build: () =>
			buildAppContext({
				theme: { requested: "default", resolved: fakeTheme },
				components: [{ slug: "button", item: fakeButton }],
				recipes: [],
			}),
		contains: ["Depends on: `popover`."],
		excludes: ["native-popover"],
	},
	{
		// Substring assertions instead of full snapshot — keeps the override case
		// scoped to what overrides actually change so unrelated cosmetic edits to
		// other sections don't churn this test.
		name: "overrides applied to highlight table + globals.css :root",
		build: () =>
			buildAppContext({
				theme: { requested: "default", resolved: fakeTheme },
				components: [{ slug: "card", item: fakeCard }],
				recipes: [],
				overrides: { primary: "230 45% 55%" },
			}),
		contains: [
			"| `--primary` | `230 45% 55%` *(override)* |",
			"--primary: 230 45% 55%;",
		],
		excludes: ["--primary: 240 5.9% 10%;"],
	},
	{
		// Density-cascade regression gate: theme already declares `--space-4: 1rem`
		// and `--control-height-md: 2.5rem`. The compact preset overrides BOTH to
		// smaller values, and we assert (a) density wins, (b) the theme value does
		// NOT also appear in `:root` (which would be a silent no-op via cascade).
		name: "compact density wins over overlapping theme tokens (cascade regression gate)",
		build: () =>
			extractRootBlock(
				buildAppContext({
					theme: { requested: "default", resolved: fakeTheme },
					components: [{ slug: "card", item: fakeCard }],
					recipes: [],
					density: "compact",
				}),
			),
		contains: [
			"--space-1: 0.125rem;",
			"--space-4: 0.75rem;",
			"--control-height-md: 2.25rem;",
		],
		excludes: [
			"--space-4: 1rem;",
			"--control-height-md: 2.5rem;",
		],
	},
	{
		name: "spacious density emits the wider preset and wins over theme",
		build: () =>
			extractRootBlock(
				buildAppContext({
					theme: { requested: "default", resolved: fakeTheme },
					components: [{ slug: "card", item: fakeCard }],
					recipes: [],
					density: "spacious",
				}),
			),
		contains: [
			"--space-1: 0.375rem;",
			"--space-4: 1.25rem;",
			"--control-height-md: 2.75rem;",
			"--control-height-lg: 3rem;",
		],
		excludes: ["--space-4: 1rem;", "--control-height-md: 2.5rem;"],
	},
	{
		// Comfortable matches token defaults — density vars are NOT folded in.
		// We assert the theme's own values appear unchanged AND no compact /
		// spacious-only keys leak in. Fixture's `--control-height-md: 2.5rem`
		// happens to equal comfortable's preset value, but the test would fail
		// if the comfortable case ever started splicing density entries (e.g.
		// `--space-1: 0.25rem` would appear, which the base theme doesn't declare).
		name: "comfortable density is a no-op (theme values pass through)",
		build: () =>
			extractRootBlock(
				buildAppContext({
					theme: { requested: "default", resolved: fakeTheme },
					components: [{ slug: "card", item: fakeCard }],
					recipes: [],
					density: "comfortable",
				}),
			),
		contains: [
			// Theme values pass through untouched — overlapping keys keep their
			// theme values, NOT the density-preset values.
			"--space-4: 1rem;",
			"--control-height-md: 2.5rem;",
		],
		excludes: [
			// Compact-only / spacious-only entries that the base theme doesn't
			// declare — if any of these leaked, comfortable would have spliced
			// density vars when it shouldn't.
			"--space-1:",
			"--gap-xs:",
			"--control-height-sm:",
			"--control-height-lg:",
		],
	},
];

const failures: string[] = [];

for (const c of CASES) {
	const actual = c.build();
	if (c.expected !== undefined && actual !== c.expected) {
		failures.push(c.name);
		console.error(`\n--- FAIL: ${c.name} ---`);
		console.error("Expected:");
		console.error(c.expected);
		console.error("\nActual:");
		console.error(actual);
		console.error("---");
		continue;
	}
	if (c.contains) {
		for (const needle of c.contains) {
			if (!actual.includes(needle)) {
				failures.push(`${c.name} (missing substring: ${needle})`);
				console.error(`\n--- FAIL: ${c.name} ---`);
				console.error(`Expected output to contain: ${needle}`);
				console.error("\nActual output:");
				console.error(actual);
				console.error("---");
			}
		}
	}
	if (c.excludes) {
		for (const needle of c.excludes) {
			if (actual.includes(needle)) {
				failures.push(`${c.name} (unexpected substring: ${needle})`);
				console.error(`\n--- FAIL: ${c.name} ---`);
				console.error(`Expected output NOT to contain: ${needle}`);
				console.error("\nActual output:");
				console.error(actual);
				console.error("---");
			}
		}
	}
}

if (failures.length > 0) {
	console.error(`\napp-context: ${failures.length} snapshot(s) failed`);
	process.exit(1);
}

console.error(`app-context: ${CASES.length} snapshots passed`);
