import * as fs from "node:fs";
import * as path from "node:path";
import type { FrameworkDetection } from "./detect-framework.js";
import { isErrnoException } from "./fs-errors.js";

/**
 * The files a React Native project needs before a `native-*` component will
 * render: the NativeWind config chain plus the token stylesheet.
 *
 * Kept beside the web init rather than inside it because almost nothing is
 * shared — native uses a Tailwind v3 config with the NativeWind preset, a
 * Metro transform, and a Babel `jsxImportSource`, none of which exist on the
 * web path.
 */

/** One file the native template writes. */
export interface TemplateFile {
	/** Cwd-relative path. */
	path: string;
	/** Full contents. */
	contents: string;
}

/** Outcome of writing one template file. */
export interface TemplateWrite {
	path: string;
	wrote: boolean;
	/** True when the file already existed and was left alone. */
	skipped: boolean;
}

/**
 * Render `tailwind.config.js` for a NativeWind project.
 *
 * NativeWind's stable line is built on Tailwind v3, so this is a CommonJS
 * config with a `presets` entry — deliberately not the v4 CSS-first shape the
 * web path emits.
 * @param extendMaps - Output of `themeToTailwindConfig`
 * @returns The config file contents
 */
export function emitNativeTailwindConfig(
	extendMaps: Record<string, Record<string, string>>,
): string {
	const extend = JSON.stringify(extendMaps, null, "\t").replace(/\n/g, "\n\t\t");
	return `/** Generated by \`hex init --platform native\`. */
/** @type {import("tailwindcss").Config} */
module.exports = {
\tdarkMode: "class",
\tcontent: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
\tpresets: [require("nativewind/preset")],
\ttheme: {
\t\textend: ${extend},
\t},
\tplugins: [],
};
`;
}

/**
 * `metro.config.js` wiring NativeWind's transformer.
 *
 * The default config comes from a different package depending on the project:
 * Expo apps have `expo/metro-config`, bare React Native apps do not — writing
 * the Expo form there makes Metro fail to start on a missing module.
 * @param bare - True for a bare React Native project (no Expo)
 * @returns The config file contents
 */
export function emitMetroConfig(bare: boolean): string {
	const defaultConfig = bare
		? `const { getDefaultConfig } = require("@react-native/metro-config");`
		: `const { getDefaultConfig } = require("expo/metro-config");`;
	return `${defaultConfig}
const { withNativeWind } = require("nativewind/metro");

const config = getDefaultConfig(__dirname);

// \`inlineRem\` resolves the rem-based radius and spacing tokens — React Native
// has no root font size for them to reference.
module.exports = withNativeWind(config, { input: "./global.css", inlineRem: 16 });
`;
}

/**
 * `babel.config.js` pointing JSX at NativeWind's runtime.
 *
 * Same split as the Metro config: the base preset differs between Expo and
 * bare React Native, and naming the wrong one breaks the transform.
 * @param bare - True for a bare React Native project (no Expo)
 * @returns The config file contents
 */
export function emitBabelConfig(bare: boolean): string {
	const basePreset = bare
		? `["module:@react-native/babel-preset", { jsxImportSource: "nativewind" }]`
		: `["babel-preset-expo", { jsxImportSource: "nativewind" }]`;
	return `module.exports = function (api) {
\tapi.cache(true);
\treturn {
\t\t// \`jsxImportSource\` is what turns \`className\` on a React Native element
\t\t// into a style. Without it every Hex component renders unstyled.
\t\tpresets: [${basePreset}, "nativewind/babel"],
\t};
};
`;
}

/** Ambient types so `className` type-checks on React Native elements. */
export const NATIVEWIND_ENV_DTS = `/// <reference types="nativewind/types" />\n`;

/** The `cn` helper every component imports. */
export const CN_HELPER = `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Merge class names with Tailwind-aware conflict resolution.
 * @param inputs - Class values to merge
 * @returns The merged class string
 */
export function cn(...inputs: ClassValue[]): string {
\treturn twMerge(clsx(inputs));
}
`;

/**
 * The npm packages a native Hex project needs.
 *
 * Split from the web list because none of it overlaps: no `tw-animate-css`,
 * no PostCSS, and Tailwind pinned to v3 for NativeWind.
 * @param bare - True for a bare React Native project (no Expo)
 * @returns The package specs to install
 */
export function nativePeerDeps(bare: boolean): string[] {
	return [
		"nativewind",
		"tailwindcss@^3.4.0",
		// The generated `babel.config.js` extends it. Recent templates ship no
		// Babel config at all, so the preset is not necessarily installed —
		// and Metro fails to construct its transformer without it.
		bare ? "@react-native/babel-preset" : "babel-preset-expo",
		"clsx",
		"tailwind-merge",
		"class-variance-authority",
		"react-native-safe-area-context",
	];
}

/**
 * Build the file set for a native project.
 * @param globalsCss - Output of `generateGlobalsCssNative`
 * @param tailwindConfig - Output of {@link emitNativeTailwindConfig}
 * @param detection - Detected framework, used to place the `cn` helper
 * @returns The files to write, in order
 */
export function nativeTemplateFiles(
	globalsCss: string,
	tailwindConfig: string,
	detection: FrameworkDetection,
	isEsmProject = false,
): TemplateFile[] {
	const libDir = detection.srcDir ? "src/lib" : "lib";
	const bare = detection.kind === "react-native";
	// All three configs are CommonJS (`require` + `module.exports`). In a
	// project whose package.json declares `"type": "module"`, a `.js` file is
	// an ES module and Metro dies with "require is not defined in ES module
	// scope". The `.cjs` extension opts them back out — which is exactly what
	// this repo's own playground does.
	const ext = isEsmProject ? "cjs" : "js";
	return [
		{ path: "global.css", contents: globalsCss },
		{ path: `tailwind.config.${ext}`, contents: tailwindConfig },
		{ path: `metro.config.${ext}`, contents: emitMetroConfig(bare) },
		{ path: `babel.config.${ext}`, contents: emitBabelConfig(bare) },
		{ path: "nativewind-env.d.ts", contents: NATIVEWIND_ENV_DTS },
		{ path: `${libDir}/utils.ts`, contents: CN_HELPER },
	];
}

/**
 * Write the template, never clobbering a file that already exists unless
 * asked.
 * @param cwd - Project root
 * @param files - Files from {@link nativeTemplateFiles}
 * @param overwrite - Decides per file whether an existing one may be replaced
 * @returns One result per file
 */
export function writeNativeTemplate(
	cwd: string,
	files: readonly TemplateFile[],
	overwrite: (filePath: string) => boolean,
): TemplateWrite[] {
	return files.map((file) => {
		const target = path.join(cwd, file.path);
		fs.mkdirSync(path.dirname(target), { recursive: true });

		if (overwrite(file.path)) {
			fs.writeFileSync(target, file.contents, "utf8");
			return { path: file.path, wrote: true, skipped: false };
		}

		// Exclusive create rather than "check, then write": `wx` fails with
		// EEXIST if the file appears between the two, so a scaffolder can
		// never clobber a file it was told to leave alone.
		let handle: number;
		try {
			handle = fs.openSync(target, "wx");
		} catch (error) {
			if (isErrnoException(error) && error.code === "EEXIST") {
				return { path: file.path, wrote: false, skipped: true };
			}
			throw error;
		}
		try {
			fs.writeFileSync(handle, file.contents, "utf8");
		} finally {
			fs.closeSync(handle);
		}
		return { path: file.path, wrote: true, skipped: false };
	});
}

/**
 * Whether the app's entry file already imports the token stylesheet.
 *
 * `hex init` does not edit the entry itself — rewriting a consumer's root
 * layout is the kind of change that silently breaks a working app — so the
 * summary tells them to add the line when it is missing.
 * @param cwd - Project root
 * @param entryHint - Cwd-relative entry path from framework detection
 * @returns True when the import is already present
 */
export function entryImportsGlobalsCss(cwd: string, entryHint: string): boolean {
	const entry = path.join(cwd, entryHint);
	if (!fs.existsSync(entry)) return false;
	return /import\s+["'].*global\.css["']/.test(fs.readFileSync(entry, "utf8"));
}
