// AUTO-GENERATED by scripts/build-barrels.ts — do not edit.
// Run `pnpm run build:barrels` (or `pnpm build`) to regenerate.

/**
 * Schema re-exports — design-time metadata for tooling that wants typed
 * access to the component manifest without pulling in runtime React.
 */

export { nativeAvatarSchema } from "./primitives/avatar/avatar.schema.js";
export { nativeBadgeSchema } from "./primitives/badge/badge.schema.js";
export { nativeButtonSchema } from "./primitives/button/button.schema.js";
export { nativeCheckboxSchema } from "./primitives/checkbox/checkbox.schema.js";
export { nativeInputSchema } from "./primitives/input/input.schema.js";
export { nativeLabelSchema } from "./primitives/label/label.schema.js";
export { nativeProgressSchema } from "./primitives/progress/progress.schema.js";
export { nativeRadioGroupSchema } from "./primitives/radio-group/radio-group.schema.js";
export { nativeSeparatorSchema } from "./primitives/separator/separator.schema.js";
export { nativeSkeletonSchema } from "./primitives/skeleton/skeleton.schema.js";
export { nativeSwitchSchema } from "./primitives/switch/switch.schema.js";
export { nativeTextSchema } from "./primitives/text/text.schema.js";
export { nativeTextareaSchema } from "./primitives/textarea/textarea.schema.js";
export { nativeAlertDialogSchema } from "./components/alert-dialog/alert-dialog.schema.js";
export { nativeBottomSheetSchema } from "./components/bottom-sheet/bottom-sheet.schema.js";
export { nativeCardSchema } from "./components/card/card.schema.js";
export { nativeDialogSchema } from "./components/dialog/dialog.schema.js";
export { nativePopoverSchema } from "./components/popover/popover.schema.js";
export { nativeSelectSchema } from "./components/select/select.schema.js";
export { nativeTabsSchema } from "./components/tabs/tabs.schema.js";
export { nativeTooltipSchema } from "./components/tooltip/tooltip.schema.js";
export { nativeComposerSchema } from "./ai/composer/composer.schema.js";
export { nativeMarkdownSchema } from "./ai/markdown/markdown.schema.js";
export { nativeMessageSchema } from "./ai/message/message.schema.js";
export { nativeMessageListSchema } from "./ai/message-list/message-list.schema.js";
export { nativeToolCallSchema } from "./ai/tool-call/tool-call.schema.js";
