/**
 * Schema re-exports — design-time metadata for tooling.
 *
 * Its own entry so the runtime barrel never imports `@hex-core/registry`
 * or the web schemas it derives from. Tooling imports from
 * `@hex-core/native/schemas`; a React Native app never needs to.
 *
 * Generated by `scripts/build-barrels.ts`.
 */
export * from "./schemas.generated.js";
