import type { Theme } from "@hex-ui/registry";

export const defaultTheme: Theme = {
	name: "default",
	displayName: "Default",
	description:
		"A refined, neutral theme with subtle depth. Professional and versatile with clean lines and balanced contrast.",
	tokens: {
		light: {
			background: { value: "0 0% 100%", type: "color" },
			foreground: { value: "240 10% 3.9%", type: "color" },
			card: { value: "0 0% 100%", type: "color" },
			"card-foreground": { value: "240 10% 3.9%", type: "color" },
			popover: { value: "0 0% 100%", type: "color" },
			"popover-foreground": { value: "240 10% 3.9%", type: "color" },
			primary: { value: "240 5.9% 10%", type: "color" },
			"primary-foreground": { value: "0 0% 98%", type: "color" },
			secondary: { value: "240 4.8% 95.9%", type: "color" },
			"secondary-foreground": { value: "240 5.9% 10%", type: "color" },
			muted: { value: "240 4.8% 95.9%", type: "color" },
			"muted-foreground": { value: "240 3.8% 46.1%", type: "color" },
			accent: { value: "240 4.8% 95.9%", type: "color" },
			"accent-foreground": { value: "240 5.9% 10%", type: "color" },
			destructive: { value: "0 84.2% 60.2%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "240 5.9% 90%", type: "color" },
			input: { value: "240 5.9% 90%", type: "color" },
			ring: { value: "240 5.9% 10%", type: "color" },
			radius: { value: "0.625rem", type: "radius" },
		},
		dark: {
			background: { value: "240 10% 3.9%", type: "color" },
			foreground: { value: "0 0% 98%", type: "color" },
			card: { value: "240 10% 3.9%", type: "color" },
			"card-foreground": { value: "0 0% 98%", type: "color" },
			popover: { value: "240 10% 3.9%", type: "color" },
			"popover-foreground": { value: "0 0% 98%", type: "color" },
			primary: { value: "0 0% 98%", type: "color" },
			"primary-foreground": { value: "240 5.9% 10%", type: "color" },
			secondary: { value: "240 3.7% 15.9%", type: "color" },
			"secondary-foreground": { value: "0 0% 98%", type: "color" },
			muted: { value: "240 3.7% 15.9%", type: "color" },
			"muted-foreground": { value: "240 5% 64.9%", type: "color" },
			accent: { value: "240 3.7% 15.9%", type: "color" },
			"accent-foreground": { value: "0 0% 98%", type: "color" },
			destructive: { value: "0 62.8% 30.6%", type: "color" },
			"destructive-foreground": { value: "0 0% 98%", type: "color" },
			border: { value: "240 3.7% 15.9%", type: "color" },
			input: { value: "240 3.7% 15.9%", type: "color" },
			ring: { value: "240 4.9% 83.9%", type: "color" },
			radius: { value: "0.625rem", type: "radius" },
		},
	},
};
