/**
 * Single source of truth for UI components in the docs app.
 * All demos and pages import from here — no duplication of component code.
 * This re-exports from @hex-ui/components so docs stay in sync with the real library.
 */
export {
	Button,
	buttonVariants,
	type ButtonProps,
	Input,
	type InputProps,
	Label,
	type LabelProps,
	Textarea,
	type TextareaProps,
	Checkbox,
	type CheckboxProps,
	Switch,
	type SwitchProps,
	Badge,
	badgeVariants,
	type BadgeProps,
	Separator,
	type SeparatorProps,
	Card,
	CardHeader,
	CardTitle,
	CardDescription,
	CardContent,
	CardFooter,
	Tabs,
	TabsList,
	TabsTrigger,
	TabsContent,
	Accordion,
	AccordionItem,
	AccordionTrigger,
	AccordionContent,
	Dialog,
	DialogPortal,
	DialogOverlay,
	DialogTrigger,
	DialogClose,
	DialogContent,
	DialogHeader,
	DialogFooter,
	DialogTitle,
	DialogDescription,
	AlertDialog,
	AlertDialogPortal,
	AlertDialogOverlay,
	AlertDialogTrigger,
	AlertDialogContent,
	AlertDialogHeader,
	AlertDialogFooter,
	AlertDialogTitle,
	AlertDialogDescription,
	AlertDialogAction,
	AlertDialogCancel,
	DropdownMenu,
	DropdownMenuTrigger,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuCheckboxItem,
	DropdownMenuRadioItem,
	DropdownMenuLabel,
	DropdownMenuSeparator,
	DropdownMenuShortcut,
	DropdownMenuGroup,
	DropdownMenuPortal,
	DropdownMenuSub,
	DropdownMenuRadioGroup,
	Popover,
	PopoverTrigger,
	PopoverContent,
	PopoverAnchor,
	Tooltip,
	TooltipTrigger,
	TooltipContent,
	TooltipProvider,
	Select,
	SelectGroup,
	SelectValue,
	SelectTrigger,
	SelectContent,
	SelectLabel,
	SelectItem,
	SelectSeparator,
	RadioGroup,
	RadioGroupItem,
	Slider,
	Toggle,
	toggleVariants,
	ToggleGroup,
	ToggleGroupItem,
	Form,
	FormItem,
	FormLabel,
	FormControl,
	FormDescription,
	FormMessage,
	FormField,
	useFormField,
	Avatar,
	AvatarImage,
	AvatarFallback,
	Skeleton,
	Progress,
	ScrollArea,
	ScrollBar,
	AspectRatio,
	Alert,
	AlertTitle,
	AlertDescription,
	alertVariants,
	Toaster,
	toast,
	cn,
} from "@hex-ui/components";
