import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { readModuleExports, type ModuleExports } from "./lib/module-exports.js";
import { writeIfChanged } from "./lib/write-if-changed.js";

/**
 * Emit every hand-maintained "list of components" from the filesystem.
 *
 * Before this script the same list existed in six places — the runtime
 * barrel, the schema barrel, the blocks barrel, the docs demo map (twice,
 * once as imports and once as map keys) and the docs re-export barrel.
 * None was derived from the others and they had already drifted: 53 of
 * 161 schemas were missing from `schemas.ts`, including all 43 blocks.
 *
 * Output is deterministic — directories are sorted and export names come
 * back sorted — so CI can diff the generated files the same way it diffs
 * `registry/`.
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const COMPONENTS_SRC = path.join(ROOT, "packages/components/src");
const NATIVE_SRC = path.join(ROOT, "packages/native/src");
const MOTION_SRC = path.join(ROOT, "packages/motion/src");
const BRIEFS_SRC = path.join(ROOT, "packages/themes/src/presets/_briefs");
const DOCS_LIB = path.join(ROOT, "apps/docs/src/lib");
const PLAYGROUND_SRC = path.join(ROOT, "apps/native-playground/src");

/**
 * One package whose `src/<category>/<slug>/` folders the generator walks.
 *
 * The web package and the React Native package share the folder convention
 * and each get their own runtime barrel, schema barrel and demo map; the
 * only differences are which categories exist and which shared modules sit
 * beside the components.
 */
interface BarrelRoot {
	src: string;
	/**
	 * Category directories, in the order they appear in the emitted barrel.
	 * Each holds one subdirectory per component containing `<slug>.tsx`
	 * and `<slug>.schema.ts`.
	 */
	categories: readonly string[];
	/**
	 * Modules that are not a single component but still contribute to the
	 * public API — shared helpers, hook aggregates, cross-block contracts.
	 *
	 * `only` narrows the re-export where a module holds more than its public
	 * surface: `lib/utils.ts` also exports `safeUrl`, which is internal.
	 * Without the allowlist, generating would silently widen the published API.
	 */
	aggregates: Array<{ module: string; only?: string[] }>;
	/** Where the demo map goes; `demos.generated.tsx` is written inside it. */
	demoLib: string;
}

const WEB_ROOT: BarrelRoot = {
	src: COMPONENTS_SRC,
	categories: ["primitives", "components", "ai", "artifacts", "blocks"],
	aggregates: [
		{ module: "lib/utils.ts", only: ["cn"] },
		{ module: "lib/color.ts" },
		{ module: "hooks/index.ts" },
		{ module: "ai/types.ts" },
		{ module: "blocks/_shared/auth-adapter.ts" },
	],
	demoLib: DOCS_LIB,
};

/**
 * Native ships no blocks or artifacts, and its demos render in the Expo
 * playground rather than the docs site — the docs demo map must never
 * import a file that pulls in `react-native`.
 */
const NATIVE_ROOT: BarrelRoot = {
	src: NATIVE_SRC,
	categories: ["primitives", "components", "ai"],
	aggregates: [
		{ module: "lib/utils.ts", only: ["cn"] },
		{ module: "lib/text-context.tsx" },
	],
	demoLib: PLAYGROUND_SRC,
};

const BANNER = `// AUTO-GENERATED by scripts/build-barrels.ts — do not edit.
// Run \`pnpm run build:barrels\` (or \`pnpm build\`) to regenerate.
`;

interface ComponentModule {
	category: string;
	slug: string;
	/**
	 * Every runtime `.tsx` in the component's folder, `<slug>.tsx` first.
	 *
	 * A folder may hold more than one — `ai/code-block/` ships both
	 * `code-block.tsx` and `code-block-copy.tsx`, and tsup already makes
	 * each its own deep-import entry, so both belong in the barrel.
	 */
	componentPaths: string[];
	/** Absolute path to `<slug>.schema.ts`, when one exists. */
	schemaPath: string | null;
	/** Absolute path to `<slug>.demo.tsx`, when one exists. */
	demoPath: string | null;
}

/** Files inside a component folder that are not part of its runtime surface. */
function isRuntimeSource(file: string): boolean {
	return (
		file.endsWith(".tsx") &&
		!file.endsWith(".demo.tsx") &&
		!file.endsWith(".test.tsx") &&
		!file.endsWith(".stories.tsx")
	);
}

/**
 * Walk the component tree and collect every component directory.
 *
 * Sorted at both levels: `readdirSync` order is filesystem-dependent
 * (APFS vs ext4) and this order reaches files that CI diffs.
 * @param root - The package to walk
 * @returns Every discovered component, ordered by category then slug
 */
function findComponents(root: BarrelRoot): ComponentModule[] {
	const found: ComponentModule[] = [];

	for (const category of root.categories) {
		const categoryDir = path.join(root.src, category);
		if (!fs.existsSync(categoryDir)) continue;

		for (const slug of fs.readdirSync(categoryDir).sort()) {
			const dir = path.join(categoryDir, slug);
			if (!fs.statSync(dir).isDirectory()) continue;

			const entry = `${slug}.tsx`;
			if (!fs.existsSync(path.join(dir, entry))) continue;

			// `<slug>.tsx` leads so the component itself heads its barrel
			// section; siblings follow in sorted order.
			const siblings = fs
				.readdirSync(dir)
				.filter((f) => isRuntimeSource(f) && f !== entry)
				.sort();

			const schemaPath = path.join(dir, `${slug}.schema.ts`);
			const demoPath = path.join(dir, `${slug}.demo.tsx`);
			found.push({
				category,
				slug,
				componentPaths: [entry, ...siblings].map((f) => path.join(dir, f)),
				schemaPath: fs.existsSync(schemaPath) ? schemaPath : null,
				demoPath: fs.existsSync(demoPath) ? demoPath : null,
			});
		}
	}

	return found;
}

/**
 * Collect demos from every source that is not a component folder.
 *
 * Two shapes contribute registry items without a `<slug>/` directory:
 * motion components, whose runtime ships from `@hex-core/motion`, and
 * schema-only items (`clip`, `use-scroll`, …) that are metadata over a
 * runtime the consumer already installs. Their demos sit beside the
 * schema that declares them, which keeps the colocation rule intact —
 * one folder still holds everything about the item.
 * @returns Slug → demo path for every non-component-folder demo
 */
function findExternalDemos(): Array<{ slug: string; demoPath: string }> {
	const roots = [
		path.join(MOTION_SRC, "components"),
		path.join(MOTION_SRC, "schemas"),
		path.join(COMPONENTS_SRC, "hooks/schemas"),
	];

	const found: Array<{ slug: string; demoPath: string }> = [];
	for (const root of roots) {
		if (!fs.existsSync(root)) continue;
		for (const entry of fs.readdirSync(root).sort()) {
			const nested = path.join(root, entry, `${entry}.demo.tsx`);
			if (fs.existsSync(nested)) {
				found.push({ slug: entry, demoPath: nested });
			} else if (entry.endsWith(".demo.tsx")) {
				found.push({ slug: entry.replace(/\.demo\.tsx$/, ""), demoPath: path.join(root, entry) });
			}
		}
	}
	return found;
}

/**
 * Render one `export { … } from "…";` statement.
 *
 * Type-only names carry the inline `type` modifier so the statement stays
 * valid under `isolatedModules`, which the package builds with.
 * @param exports - The module's value and type exports
 * @param specifier - The `from` specifier, `.js`-suffixed per the ESM convention
 * @param only - When present, restrict the re-export to these names
 * @returns The statement, or null when nothing survives the filter
 */
function renderExport(
	exports: ModuleExports,
	specifier: string,
	only?: string[],
): string | null {
	const keep = (name: string): boolean => only === undefined || only.includes(name);
	const names = [
		...exports.values.filter(keep),
		...exports.types.filter(keep).map((t) => `type ${t}`),
	];
	if (names.length === 0) return null;
	return `export { ${names.join(", ")} } from "${specifier}";`;
}

/**
 * Find the component a demo module exports.
 *
 * Read from the file rather than derived from the slug: naive
 * PascalCasing gets acronyms wrong (`input-otp` exports `InputOTPDemo`,
 * not `InputOtpDemo`), and a convention the generator has to guess at is
 * a convention that will eventually be broken.
 * @param demoPath - Absolute path to a `<slug>.demo.tsx`
 * @param slug - The component slug, for the error message
 * @returns The exported symbol name
 * @throws When the module exports no `*Demo` binding
 */
function demoSymbol(demoPath: string, slug: string): string {
	const exported = readModuleExports(demoPath).values.filter((name) => name.endsWith("Demo"));
	if (exported.length !== 1) {
		throw new Error(
			`${slug}: expected exactly one \`*Demo\` export in ${path.basename(demoPath)}, ` +
				`found ${exported.length === 0 ? "none" : exported.join(", ")}`,
		);
	}
	return exported[0];
}

/**
 * Build the runtime barrel — `@hex-core/components` or `@hex-core/native`.
 * @param components - Every discovered component
 * @param root - The package the components came from
 * @returns The file contents
 */
function renderRuntimeBarrel(components: ComponentModule[], root: BarrelRoot): string {
	const lines: string[] = [BANNER];

	for (const category of root.categories) {
		const inCategory = components.filter((c) => c.category === category);
		if (inCategory.length === 0) continue;

		lines.push(`\n// ─── ${category} ───`);
		for (const component of inCategory) {
			for (const modulePath of component.componentPaths) {
				const base = path.basename(modulePath, ".tsx");
				const statement = renderExport(
					readModuleExports(modulePath),
					`./${category}/${component.slug}/${base}.js`,
				);
				if (statement) lines.push(statement);
			}
		}
	}

	lines.push("\n// ─── shared ───");
	for (const { module, only } of root.aggregates) {
		const abs = path.join(root.src, module);
		// No existsSync guard: readModuleExports returns an empty surface for
		// a missing file, which renderExport turns into null and the caller
		// skips — same outcome, without a check-then-read race.
		const specifier = `./${module.replace(/\.tsx?$/, ".js")}`;
		const statement = renderExport(readModuleExports(abs), specifier, only);
		if (statement) lines.push(statement);
	}

	return `${lines.join("\n")}\n`;
}

/**
 * Build the schema barrel — `@hex-core/components/schemas`.
 *
 * Every component that ships a `.schema.ts` appears here. The previous
 * hand-written barrel had drifted to 109 of 161.
 * @param components - Every discovered component
 * @returns The file contents
 */
function renderSchemaBarrel(components: ComponentModule[]): string {
	const lines: string[] = [
		BANNER,
		`
/**
 * Schema re-exports — design-time metadata for tooling that wants typed
 * access to the component manifest without pulling in runtime React.
 */
`.trim(),
		"",
	];

	for (const component of components) {
		if (!component.schemaPath) continue;
		const statement = renderExport(
			readModuleExports(component.schemaPath),
			`./${component.category}/${component.slug}/${component.slug}.schema.js`,
		);
		if (statement) lines.push(statement);
	}

	return `${lines.join("\n")}\n`;
}

/**
 * Build the docs demo map.
 *
 * Static imports are deliberate: each docs route is statically generated
 * via `generateStaticParams`, so Next already emits a per-route chunk that
 * pulls in only the demo that route renders.
 *
 * Imports target workspace *source* rather than built `dist`, because
 * demos are excluded from the package's tsup entries — they exist to
 * document the library, not to ship inside it.
 * @param components - Components from one barrel root
 * @param externalDemos - Demos that live outside a component folder
 * @param demoLib - The directory the map is written into; imports are relative to it
 * @returns The file contents
 */
function renderDemoMap(
	components: ComponentModule[],
	externalDemos: Array<{ slug: string; demoPath: string }>,
	demoLib: string,
): string {
	const entries = [
		// `flatMap` rather than `filter` + a cast: it narrows `demoPath` to
		// `string` on its own, and the repo bans `as` assertions.
		...components.flatMap((c) =>
			c.demoPath === null ? [] : [{ slug: c.slug, demoPath: c.demoPath }],
		),
		...externalDemos,
	]
		.sort((a, b) => a.slug.localeCompare(b.slug))
		.map(({ slug, demoPath }) => ({ slug, demoPath, symbol: demoSymbol(demoPath, slug) }));

	const imports = entries.map(({ demoPath, symbol }) => {
		const rel = path.relative(demoLib, demoPath).replace(/\.tsx$/, "").split(path.sep).join("/");
		return `import { ${symbol} } from "${rel}";`;
	});

	const mapEntries = entries.map(({ slug, symbol }) => {
		const key = /^[a-zA-Z_$][\w$]*$/.test(slug) ? slug : JSON.stringify(slug);
		return `\t${key}: ${symbol},`;
	});

	return `${BANNER}
import type { ComponentType } from "react";
${imports.join("\n")}

/** Map of component slug → rendered demo component. */
export const demos: Record<string, ComponentType> = {
${mapEntries.join("\n")}
};

/**
 * Look up a demo component by registry slug.
 * @param slug - The component's registry name (e.g. "button")
 * @returns The demo component, or undefined if the component ships no demo
 */
export function getDemo(slug: string): ComponentType | undefined {
	return demos[slug];
}
`;
}

/**
 * Build the lazy brief-loader map for `@hex-core/themes`.
 *
 * This was a 71-arm `switch`, every arm mechanically identical. It cannot
 * become a template-literal dynamic import: esbuild only code-splits
 * `import()` calls whose argument is a string literal, and the briefs are
 * kept out of the main chunk on purpose — they cost roughly 22KB each and
 * only Studio's copy flow reads them.
 *
 * So the imports stay static and the list stops being hand-written.
 * @returns The file contents
 */
function renderBriefLoaders(): string {
	const slugs = fs
		.readdirSync(BRIEFS_SRC)
		.filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"))
		.map((f) => path.basename(f, ".ts"))
		.sort();

	const entries = slugs.map((slug) => {
		const exported = readModuleExports(path.join(BRIEFS_SRC, `${slug}.ts`)).values.filter((name) =>
			name.endsWith("Brief"),
		);
		if (exported.length !== 1) {
			throw new Error(
				`${slug}: expected exactly one \`*Brief\` export, found ` +
					`${exported.length === 0 ? "none" : exported.join(", ")}`,
			);
		}
		const key = /^[a-zA-Z_$][\w$]*$/.test(slug) ? slug : JSON.stringify(slug);
		return `\t${key}: async () => (await import("./_briefs/${slug}.js")).${exported[0]},`;
	});

	return `${BANNER}
/**
 * Lazy loaders for each preset's original markdown design brief, keyed by
 * slug. Briefs are not inlined on the preset object so the top-level
 * \`@hex-core/themes\` barrel stays tree-shakeable — agents that only want
 * token data never pay the per-brief cost.
 */
export const briefLoaders: Record<string, () => Promise<string>> = {
${entries.join("\n")}
};
`;
}

const components = findComponents(WEB_ROOT);
const externalDemos = findExternalDemos();

const outputs: Array<{ path: string; content: string }> = [
	{
		path: path.join(COMPONENTS_SRC, "index.generated.ts"),
		content: renderRuntimeBarrel(components, WEB_ROOT),
	},
	{
		path: path.join(COMPONENTS_SRC, "schemas.generated.ts"),
		content: renderSchemaBarrel(components),
	},
	{
		path: path.join(WEB_ROOT.demoLib, "demos.generated.tsx"),
		content: renderDemoMap(components, externalDemos, WEB_ROOT.demoLib),
	},
	{
		path: path.join(ROOT, "packages/themes/src/presets/briefs.generated.ts"),
		content: renderBriefLoaders(),
	},
];

// The native package is optional on disk (it lands after this generator
// learned about it) and its demo map only makes sense once the playground
// app exists to import it.
const nativeComponents = fs.existsSync(NATIVE_ROOT.src) ? findComponents(NATIVE_ROOT) : [];
if (fs.existsSync(NATIVE_ROOT.src)) {
	outputs.push(
		{
			path: path.join(NATIVE_SRC, "index.generated.ts"),
			content: renderRuntimeBarrel(nativeComponents, NATIVE_ROOT),
		},
		{
			path: path.join(NATIVE_SRC, "schemas.generated.ts"),
			content: renderSchemaBarrel(nativeComponents),
		},
	);
	if (fs.existsSync(NATIVE_ROOT.demoLib)) {
		outputs.push({
			path: path.join(NATIVE_ROOT.demoLib, "demos.generated.tsx"),
			content: renderDemoMap(nativeComponents, [], NATIVE_ROOT.demoLib),
		});
	}
}

console.log("\nGenerating Hex Core barrels...\n");

for (const output of outputs) {
	const changed = writeIfChanged(output.path, output.content);
	console.log(`  ${changed ? "→" : "="} ${path.relative(ROOT, output.path)}`);
}

const all = [...components, ...nativeComponents];
const withSchema = all.filter((c) => c.schemaPath).length;
const withDemo = all.filter((c) => c.demoPath).length + externalDemos.length;
console.log(
	`\n✓ Barrels built: ${String(components.length)} web + ${String(nativeComponents.length)} native components, ` +
		`${String(withSchema)} schemas, ${String(withDemo)} demos`,
);
