// AUTO-GENERATED by scripts/build-barrels.ts — do not edit.
// Run `pnpm run build:barrels` (or `pnpm build`) to regenerate.

import type { ComponentType } from "react";
import { AlertDialogDemo } from "../../../packages/native/src/components/alert-dialog/alert-dialog.demo";
import { AvatarDemo } from "../../../packages/native/src/primitives/avatar/avatar.demo";
import { BadgeDemo } from "../../../packages/native/src/primitives/badge/badge.demo";
import { BottomSheetDemo } from "../../../packages/native/src/components/bottom-sheet/bottom-sheet.demo";
import { ButtonDemo } from "../../../packages/native/src/primitives/button/button.demo";
import { CardDemo } from "../../../packages/native/src/components/card/card.demo";
import { CheckboxDemo } from "../../../packages/native/src/primitives/checkbox/checkbox.demo";
import { ComposerDemo } from "../../../packages/native/src/ai/composer/composer.demo";
import { DialogDemo } from "../../../packages/native/src/components/dialog/dialog.demo";
import { InputDemo } from "../../../packages/native/src/primitives/input/input.demo";
import { LabelDemo } from "../../../packages/native/src/primitives/label/label.demo";
import { MarkdownDemo } from "../../../packages/native/src/ai/markdown/markdown.demo";
import { MessageDemo } from "../../../packages/native/src/ai/message/message.demo";
import { MessageListDemo } from "../../../packages/native/src/ai/message-list/message-list.demo";
import { PopoverDemo } from "../../../packages/native/src/components/popover/popover.demo";
import { ProgressDemo } from "../../../packages/native/src/primitives/progress/progress.demo";
import { RadioGroupDemo } from "../../../packages/native/src/primitives/radio-group/radio-group.demo";
import { SelectDemo } from "../../../packages/native/src/components/select/select.demo";
import { SeparatorDemo } from "../../../packages/native/src/primitives/separator/separator.demo";
import { SkeletonDemo } from "../../../packages/native/src/primitives/skeleton/skeleton.demo";
import { SwitchDemo } from "../../../packages/native/src/primitives/switch/switch.demo";
import { TabsDemo } from "../../../packages/native/src/components/tabs/tabs.demo";
import { TextDemo } from "../../../packages/native/src/primitives/text/text.demo";
import { TextareaDemo } from "../../../packages/native/src/primitives/textarea/textarea.demo";
import { ToolCallDemo } from "../../../packages/native/src/ai/tool-call/tool-call.demo";
import { TooltipDemo } from "../../../packages/native/src/components/tooltip/tooltip.demo";

/** Map of component slug → rendered demo component. */
export const demos: Record<string, ComponentType> = {
	"alert-dialog": AlertDialogDemo,
	avatar: AvatarDemo,
	badge: BadgeDemo,
	"bottom-sheet": BottomSheetDemo,
	button: ButtonDemo,
	card: CardDemo,
	checkbox: CheckboxDemo,
	composer: ComposerDemo,
	dialog: DialogDemo,
	input: InputDemo,
	label: LabelDemo,
	markdown: MarkdownDemo,
	message: MessageDemo,
	"message-list": MessageListDemo,
	popover: PopoverDemo,
	progress: ProgressDemo,
	"radio-group": RadioGroupDemo,
	select: SelectDemo,
	separator: SeparatorDemo,
	skeleton: SkeletonDemo,
	switch: SwitchDemo,
	tabs: TabsDemo,
	text: TextDemo,
	textarea: TextareaDemo,
	"tool-call": ToolCallDemo,
	tooltip: TooltipDemo,
};

/**
 * Look up a demo component by registry slug.
 * @param slug - The component's registry name (e.g. "button")
 * @returns The demo component, or undefined if the component ships no demo
 */
export function getDemo(slug: string): ComponentType | undefined {
	return demos[slug];
}
